import type { App } from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import delle icone che vuoi utilizzare
import {
  // Icone comuni
  faUser,
  faUsers,
  faHome,
  faCog,
  faSearch,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faQuestionCircle,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendar,
  faCalendarAlt,
  faClock,
  faEye,
  faEyeSlash,
  faDownload,
  faUpload,
  faPrint,
  faShare,
  faLink,
  faExternalLinkAlt,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faRefresh,
  faSpinner,
  faCircleNotch,
  // Dashboard e HR
  faTachometerAlt,
  faChartBar,
  faChartLine,
  faChartPie,
  faTable,
  faFileAlt,
  faFilePdf,
  faFileExcel,
  faFolder,
  faFolderOpen,
  // Utenti e gestione
  faUserPlus,
  faUserMinus,
  faUserCog,
  faUserTie,
  faUserCircle,
  faIdCard,
  faBuilding,
  faBriefcase,
  // Finanze
  faEuroSign,
  faMoneyBillWave,
  faMoneyCheckAlt,
  faCalculator,
  faCreditCard,
  faCoins,
  // Azioni
  faSignOutAlt,
  faSignInAlt,
  faPowerOff,
  faLock,
  faUnlock,
  faKey,
  faShieldAlt,
  // Social e comunicazione
  faComment,
  faComments,
  faInbox,
  faPaperPlane,
  // Stati
  faCheckCircle,
  faTimesCircle,
  faExclamationCircle,
  faMinusCircle,
  faPlusCircle,
  // Tempo e date
  faCalendarCheck,
  faCalendarTimes,
  faCalendarPlus,
  faStopwatch,
  faHourglass,
  // Utilità
  faEllipsisV,
  faEllipsisH,
  faGripLines,
  faSortUp,
  faSortDown,
  faSort,
  faFilter,
  faSliders,
} from '@fortawesome/free-solid-svg-icons'

import {
  // Icone regular che potrebbero servire
  faUser as farUser,
  faEnvelope as farEnvelope,
  faCalendar as farCalendar,
  faCheckCircle as farCheckCircle,
  faTimesCircle as farTimesCircle,
  faFile as farFile,
  faFolder as farFolder,
  faClock as farClock,
} from '@fortawesome/free-regular-svg-icons'

import {
  // Brand icons se necessarie
  faGoogle,
  faMicrosoft,
  faLinkedin,
  faTwitter,
  faFacebook,
} from '@fortawesome/free-brands-svg-icons'

// Configurazione della libreria
library.add(
  // Solid icons
  faUser,
  faUsers,
  faHome,
  faCog,
  faSearch,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faQuestionCircle,
  faBell,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faCalendar,
  faCalendarAlt,
  faClock,
  faEye,
  faEyeSlash,
  faDownload,
  faUpload,
  faPrint,
  faShare,
  faLink,
  faExternalLinkAlt,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faRefresh,
  faSpinner,
  faCircleNotch,
  faTachometerAlt,
  faChartBar,
  faChartLine,
  faChartPie,
  faTable,
  faFileAlt,
  faFilePdf,
  faFileExcel,
  faFolder,
  faFolderOpen,
  faUserPlus,
  faUserMinus,
  faUserCog,
  faUserTie,
  faUserCircle,
  faIdCard,
  faBuilding,
  faBriefcase,
  faEuroSign,
  faMoneyBillWave,
  faMoneyCheckAlt,
  faCalculator,
  faCreditCard,
  faCoins,
  faSignOutAlt,
  faSignInAlt,
  faPowerOff,
  faLock,
  faUnlock,
  faKey,
  faShieldAlt,
  faComment,
  faComments,
  faInbox,
  faPaperPlane,
  faCheckCircle,
  faTimesCircle,
  faExclamationCircle,
  faMinusCircle,
  faPlusCircle,
  faCalendarCheck,
  faCalendarTimes,
  faCalendarPlus,
  faStopwatch,
  faHourglass,
  faEllipsisV,
  faEllipsisH,
  faGripLines,
  faSortUp,
  faSortDown,
  faSort,
  faFilter,
  faSliders,
  
  // Regular icons
  farUser,
  farEnvelope,
  farCalendar,
  farCheckCircle,
  farTimesCircle,
  farFile,
  farFolder,
  farClock,
  
  // Brand icons
  faGoogle,
  faMicrosoft,
  faLinkedin,
  faTwitter,
  faFacebook
)

export const installFontAwesome = (app: App): void => {
  // Registra il componente FontAwesome globalmente
  app.component('FontAwesomeIcon', FontAwesomeIcon)
  app.component('FaIcon', FontAwesomeIcon) // Alias più corto
}

// Esporta FontAwesome per uso diretto se necessario
export { FontAwesomeIcon, library }

// Esporta anche i tipi utili
export type { IconDefinition } from '@fortawesome/fontawesome-svg-core'